### ISSUE TITLE
Request to Add User-Agent Header to reqwest Client for JWKS Requests

### ISSUE THREAD

**Issue by shiote2** [lmammino/oidc-authorizer#22]
**Description:**
Requests to fetch the JWKS (JSON Web Key Set) are being blocked by AWS WAF due to the absence of a User-Agent header. The NoUserAgent_HEADER rule in the AWSManagedRulesCommonRuleSet requires a User-Agent header to be present in the request.

**Solution:**
Add a User-Agent header to the reqwest client used for making JWKS requests. This will ensure compliance with the WAF rules and prevent requests from being blocked. You can modify the User-Agent to suit your needs.

**Affected Area:**
Module: keysmap::KeysMap
Function: refresh in KeysStorage
Proposed Implementation:
`client: Client::builder().user_agent("oidc-authorizer/0.1.0").build().unwrap()`

**Additional Context:**
This change will help in maintaining uninterrupted communication with AWS services by adhering to the security rules configured in AWS WAF.

**Relevant PR:**
Please see the related PR for more details and discussions: [#21](https://github.com/lmammino/oidc-authorizer/pull/21)

**Comment by lmammino** [comment]
Closed by #21
