### ISSUE TITLE
Bug: Claim 'aud' is not a string

### ISSUE THREAD

**Issue by lorenzobrusco** [lmammino/oidc-authorizer#8]
I've tried to configure audience inside env variable, but Auth0 inside the jwt for aud claims use a list of value and the application return this error:

**Claim 'aud' is not a string**

this is an example of aud claims:
~~~
{
  "aud": [
      "aud1",
      "aud2"
    ]
}
~~~

**Comment by lmammino** [comment]
Hello @lorenzobrusco and thanks for opening this issue.

I haven't seen this kind of use case implemented by any identity provider I have used so far.

I was trying to research more details and I couldn't find any official documentation describing this behavior. Do you have a link with more details?

So far I could only find support tickets ([this one](https://community.auth0.com/t/implement-multiple-audiences-in-an-access-token/98871/7) is the most recent) that say this feature is not supported by Auth0...

Supporting this feature would require a fair bit of work and significant added complexity, so I'd like to make sure this is a common enough use case and that I do understand the spec for it...

**Comment by markdespain** [comment]
I'm not strongly familiar either, but FWIW it looks like the JWT RFC mentions that "aud" can be either an array of strings or a single string.

https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3

**Comment by lmammino** [comment]
This is now fixed and it's being released as part of version `0.0.7`

![Bond, James Bond!](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ3BzcTN6dzh4bTRsc254NXM2MGZwZzAxdTlkNzBzcDczems1NmVkeCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/b9DzOe5w6c7UsDl5b1/giphy.gif)
